version: '3'
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes: 
      - ./api:/app
      - ./app/node_modules
  courses:
    build: • /courses_react_app
    container_name: course_c
    ports:'3000:3000'
    volumes :
      - ./courses_react_app:/app
      - ./app/node_modules
    stdin_open: true
    tty: true